# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb5d5fc677782075fcca2e20cfbd19e449ed904a9e844143255c1828067320290331e18fac704ffa697a8342b19fa1bb92c187aa48e56a382b364663c241c56a

test:
  secret_key_base: 5c65e2dca80a6427fdeae348710eefd87454328c14c56d42dab724cbc96feebe04d1f6223169af3f29a81ee503b8ad0cdc183e3ae94831309b03c0abb9eb1858

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
